apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-username
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-root-password
# The three dashes above separate two service. Two service in one deployment
---
apiVersion: v1
kind: service
metadata:
  # the name is random name.
  name: mongodb-service
spec:
  selector:
    # the app value must be the same of the pod name [row 6]
    app: mongodb
  # now the ports
  ports:
    - protocol: TCP
      # the service port
      port: 27017
      #the container port of deployment.
      targetPort: 27017
