# API version
apiVersion: v1
#  specify the TYPE of the service in this case secret for password
# and username storing data.
kind: Secret
# here you can specify the main caratteristics of the service
metadata:
  # the name
  name: mongodb-secret
# Opaque is the default srt value key-pair . The other are SSL, certificate and so on.
type: Opaque
data:
  # the name came from the specifications that you retrieve from Docker Hub
  # the values must be base64 encoded! => go to terminal.
  mongo-root-username: Y2xhdWRpb25l
  mongo-root-password: Y2xhdWRpb25lcHdk
