apiVersion: v1
kind: ConfigMap
metadata:
  name: mongodb-configmap
data:
  # Notice: the database url is the name of the service you can retrieve from
  # mongodb deployment  yaml file
  database_url: mongodb-service
